const ENVIRONMENT = process.env.ENVIRONMENT;
const SOLID_PROVIDER_URL = process.env.SOLID_PROVIDER_URL;
const SOLID_PASSWORD = process.env.SOLID_PASSWORD;
const SOLID_USERNAME = process.env.SOLID_USERNAME;
const SOLID_WEBID = process.env.SOLID_WEBID;

export {
  ENVIRONMENT,
  SOLID_PASSWORD,
  SOLID_USERNAME,
  SOLID_WEBID,
  SOLID_PROVIDER_URL
};
