dist: bionic

language: node_js
node_js:
  - "8"
  - "10"
  - "12"

cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install --frozen-lockfile
script:
  - yarn test
